name: Build and test

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_call:
    inputs:
      mod_release:
        type: boolean
        required: true
      hexdoc_release:
        type: boolean
        required: true
      dry_run:
        type: boolean
        required: true
  workflow_dispatch:

permissions:
  contents: read

env:
  # adding a branch name here will make hexdoc deploy prerelease versions of your web book on every push to that branch
  # for example: https://hexcasting.hexxy.media/v/latest/main/en_us/
  HEXDOC_BRANCHES: '["main"]'

jobs:
  build-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: mediatransport
      - name: Clone Figura
        uses: actions/checkout@v5
        with:
          repository: penguinencounter/Figura
          filter: tree:0
          fetch-depth: 0
          ref: maven-server-common
          path: figura

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Prepare Figura
        run: pushd figura && ./gradlew publishToMavenLocal --build-cache; popd

      - name: Build mod
        env:
          RELEASE: ${{ inputs.mod_release == true }}
        run: pushd mediatransport && ./gradlew build; popd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: mediatransport/build/ciArtifacts/
          if-no-files-found: error

  build-hexdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: read
    outputs:
      pages-url: ${{ steps.build.outputs.pages-url }}
      deploy: ${{ github.event_name != 'pull_request' && contains(fromJson(env.HEXDOC_BRANCHES), github.ref_name) && !inputs.dry_run }}
    steps:
      - uses: actions/checkout@v5

      - uses: hexdoc-dev/actions/setup@v1
        with:
          python-version: 3.11

      - id: build
        uses: hexdoc-dev/actions/build@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release: ${{ inputs.hexdoc_release == true }}

  deploy-pages:
    needs:
      - build-hexdoc
    if: needs.build-hexdoc.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    concurrency:
      group: hexdoc-deploy-pages
      cancel-in-progress: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: hexdoc-dev/actions/setup@v1
        with:
          python-version: 3.11
        
      - name: Merge new hexdoc build into existing book
        uses: hexdoc-dev/actions/merge@v1
        with:
          release: ${{ inputs.hexdoc_release == true }}
          site-url: ${{ needs.build-hexdoc.outputs.pages-url }}

      # if you want to add extra things to your website (eg. Javadoc/Dokka), add it to _site/dst/docs here

      - name: Deploy to Pages
        uses: hexdoc-dev/actions/deploy-pages@v1
        with:
          merge: false
          release: ${{ inputs.hexdoc_release == true }}
